### ISSUE TITLE
Is there any way to get string table quickly？

### ISSUE THREAD

**Issue by liuxincheng** [williballenthin/python-idb#107]
![image](https://user-images.githubusercontent.com/11869191/120622223-32695d00-c491-11eb-947e-8a40d9e0ed18.png)

**Comment by williballenthin** [comment]
you can use the `idautils.strings` API provided by the idapython emulation layer

https://github.com/williballenthin/python-idb/blob/768c1d1a06f413d19e2da5ffc9091bc82f54557a/idb/idapython.py#L2414

**Comment by liuxincheng** [comment]
> you can use the `idautils.strings` API provided by the idapython emulation layer
> 
> https://github.com/williballenthin/python-idb/blob/768c1d1a06f413d19e2da5ffc9091bc82f54557a/idb/idapython.py#L2414

Thank you very much. I tried and succeeded. 
I have a new problem. How can I get the function call parameters? I can get the function name. Now I want to get the actual parameter value.
![image](https://user-images.githubusercontent.com/11869191/120949242-b152e400-c776-11eb-929f-1e5f440bc0e8.png)

**Comment by williballenthin** [comment]
computing the function parameters, as above, relies on the hex-rays decompiler. this information isn't stored within the idb, to my knowledge. so, this won't be feasible using this library.

if you have access to IDA and Hex-Rays, you can use the scripting interfaces provided by those tools to recover the arguments.

**Comment by liuxincheng** [comment]
Thank you!
