### ISSUE TITLE
Is there any way to get function call parameters?

### ISSUE THREAD

**Issue by liuxincheng** [williballenthin/python-idb#108]
How can I get the function call parameters? I can get the function name. Now I want to get the function name and actual parameter value. In this I hope for your help. For example, the function and parameter relationship in the figure below
![image](https://user-images.githubusercontent.com/11869191/120949335-db0c0b00-c776-11eb-8dee-11839a67b173.png)

**Comment by williballenthin** [comment]
computing the function parameters, as above, relies on the hex-rays decompiler. this information isn't stored within the idb, to my knowledge. so, this won't be feasible using this library.

if you have access to IDA and Hex-Rays, you can use the scripting interfaces provided by those tools to recover the arguments.

**Comment by liuxincheng** [comment]
Thank you

**Comment by liuxincheng** [comment]
> computing the function parameters, as above, relies on the hex-rays decompiler. this information isn't stored within the idb, to my knowledge. so, this won't be feasible using this library.
> 
> if you have access to IDA and Hex-Rays, you can use the scripting interfaces provided by those tools to recover the arguments.

Can I get the function address, parse the assembly code and deduce the function parameters？

**Comment by williballenthin** [comment]
> Can I get the function address, parse the assembly code and deduce the function parameters？

certainly. and within IDAPython, you can use the `idaapi.get_arg_addrs` API described here: https://reverseengineering.stackexchange.com/a/17630/17194
you'll still have to do a bit of work to figure out how to decode these arguments (immediately, memory dereference, register value, etc), but it will work in many cases.
