### ISSUE TITLE
add tests demonstrating complex type handling in function signature extraction

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/python-idb#17]
show how `idb.analysis.Function.get_signature()` handles return/argument types that are:
  - simple (int, float, bool)
  - complex (struct, enum)

it would be nice to easily tell if a type is simple vs complex, and if complex, to somehow resolve it. that is, if enum, fetch the enum id and therefore enum itself, and if struct, fetch the struct id, and therefore the struct definition object itself.

see #16 for parent issue.

**Comment by XVilka** [comment]
Should be easier once https://github.com/williballenthin/python-idb/pull/82 is merged (it implements/improves [`ida_typeinf`](https://www.hex-rays.com/products/ida/support/idapython_docs/ida_typeinf-module.html) and [`ida_struct`](https://www.hex-rays.com/products/ida/support/idapython_docs/ida_struct-module.html)) modules.

**Comment by XVilka** [comment]
Fixed in https://github.com/williballenthin/python-idb/commit/252155cf038f896b493d0bbd06bcfaacf99eec35
