### ISSUE TITLE
add handling of more function calling conventions

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/python-idb#18]
within `idb.analysis.Function.get_signature()` we currently guess how to extract the calling convention, and also only support detection of `stdcall`. need to be able to handle more calling convention types.

these include:
  - `cdecl`
  - `fastcall`
  - `usercall` with extraction of which register/stack locations are used

add tests that demonstrate that this functionality works and how to use it.

ref parent issue: #16

**Comment by XVilka** [comment]
Fixed in https://github.com/williballenthin/python-idb/commit/252155cf038f896b493d0bbd06bcfaacf99eec35
