### ISSUE TITLE
Add support for IDA 5.0 .idb files

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/python-idb#26]
Add support for IDA 5.0 .idb files, as suggested by Anthony DeRosa.

**Comment by williballenthin** [comment]
this will take a bit of work, but its not impossible.

the file header has some changes, mainly using 32-bit pointers instead of 64-bits. the btree version will be different, so we'll have to detect this and swap out the btree implementation as necessary. i have no idea what the analysis-level differences will be. im worried there will be a lot of differences there. perhaps we'll start by exposing only a minimal analysis API for .idb files from version 5.0.

**Comment by williballenthin** [comment]
Hex-Rays just released a new demo version of IDA Pro that's based on IDA 7.0. With this in mind, it may not be worth the effort of implementing 5.0 support in python-idb. I presume all freely-created .idb files will soon be v7.0.

**Comment by XVilka** [comment]
Still worth the effort, imho, since there are tons of the already available IDBs for 5.0 version.

**Comment by XVilka** [comment]
Fixed in https://github.com/williballenthin/python-idb/commit/58de7fec847f1b498d9325a549b4e71452b23337
