### ISSUE TITLE
Add support for get_func_cmt()

### ISSUE THREAD

**Issue by freetink3r** [williballenthin/python-idb#30]
The idc.GetCommentEx() function does not retrieve comments that happen to be placed on the first instruction of a function. IDA Pro exposes these comments via get_func_cmt(). This ticket is to add support for get_func_cmt() so that comments on the first instruction of a function can be retrieved.

**Comment by williballenthin** [comment]
regression test showing issue added in 3b19444f016734065fa80a7e53be37060beda802

**Comment by williballenthin** [comment]
implemented `ida_funcs.get_func_cmt` in 4f1471c6672649f72097681748bb2162821b7c8f. note that i think this is the more correct place to import the function from (as opposed to `idc`, which was the old-school dumping ground for most APIs).
