### ISSUE TITLE
TIL section parsing support

### ISSUE THREAD

**Issue by XVilka** [williballenthin/python-idb#37]
I know it is not yet supported, but would be nice to have the issue at least to track the progress (if there will be any)

**Comment by Maijin** [comment]
https://github.com/aerosoul94/tilutil

**Comment by XVilka** [comment]
There is some information about types (from the IDA runtime point of view though) is available in IDA Pro import extension in GHIDRA.

**Comment by XVilka** [comment]
Fixed since https://github.com/williballenthin/python-idb/commit/c192b72ae5e81414d0218f8e28a73c83bacaf050

Is anyone has an issue with that code or a missing feature - please open a separate bug.
