### ISSUE TITLE
API Request idautils.Names()

### ISSUE THREAD

**Issue by ulabs-sgiroux** [williballenthin/python-idb#44]
This is useful for exporting named locations from an IDB into other tools.

I am not familiar with the IDB file format, but the structure of this idautils function is very similar to Entries() and Segments()

```    for i in xrange(ida_name.get_nlist_size()):
        ea   = ida_name.get_nlist_ea(i)
        name = ida_name.get_nlist_name(i)
        yield (ea, name)
```

I would rather not iterate through EAs in multiple sections, but I suppose doing this and checking flags is an alternate method.

**Comment by ulabs-sgiroux** [comment]
Should we be using netnode.name() similar to 
https://github.com/williballenthin/python-idb/blob/897db3ce9a9495ac5848aed2cb8849693cec714d/idb/idapython.py#L1373-L1376

**Comment by williballenthin** [comment]
added support in dd1a7c7  for `idautils.Names` and `ida_name.get_nlist_*` routines. these are implemented by parsing the NAM section of the .idb file. this section contains a list of pointers to named locations within the database. therefore, I expect this routine to be quite quick, and substantially more efficient than naively enumerating EAs across segments.

@ulabs-sgiroux would you see how these work for you from the `master` branch, and once confirmed, i'll tag a new release and push to PyPI?

**Comment by ulabs-sgiroux** [comment]
I'm testing this out; I have some issues to create and document before exercising the Names feature. I will create separate issues as they're not directly related to the feature.
