### ISSUE TITLE
hash calculation 

### ISSUE THREAD

**Issue by TakahiroHaruyama** [williballenthin/python-idb#49]
Could you implement the following hash calculation APIs when you have a chance? Thanks.

ida_nalt.retrieve_input_file_sha256()
ida_nalt.retrieve_input_file_md5()

**Comment by williballenthin** [comment]
implemented!

**Comment by TakahiroHaruyama** [comment]
Great!! Thanks!

**Comment by TakahiroHaruyama** [comment]
Hi the test code is correct? I got "AttributeError: ida_nalt instance has no attribute 'retrieve_input_file_sha256'".

`   
    import idb # python-idb
    with idb.from_file(idb_path) as db:
        api = idb.IDAPython(db)
        sha256 = api.ida_nalt.retrieve_input_file_sha256()
    print sha256
`

**Comment by TakahiroHaruyama** [comment]
I just used from pip, so please ignore.

**Comment by williballenthin** [comment]
I haven't pushed a minor release to pypi yet. Probably going to wait for a few more features and/or bug fixes. Let me know if you need a point release pushed.

**Comment by LusKrew** [comment]
I'm still getting this error, what's the problem? using the same code from above still causes the error "AttributeError: ida_nalt instance has no attribute 'retrieve_input_file_sha256'".

**Comment by LusKrew** [comment]
I'm still getting the same error, how am i suppose to use it? 

using sha256 = api.ida_nalt.retrieve_input_file_sha256() will cause this error : 

"AttributeError: ida_nalt instance has no attribute 'retrieve_input_file_sha256'".

tried with both python2 and python3, installed this using pip
