### ISSUE TITLE
No handlers could be found for logger "idb.fileformat"

### ISSUE THREAD

**Issue by TakahiroHaruyama** [williballenthin/python-idb#50]
Hi sorry again. When I use idb.from_file(idb_path), I got the following message. How can I suppress it?

No handlers could be found for logger "idb.fileformat"

**Comment by williballenthin** [comment]
to suppress this message, you'll probably want to configure logging prior to invoking this library. something like:

```
import logging
logging.basicConfig(level=logging.INFO)
```

**Comment by TakahiroHaruyama** [comment]
ok thanks!
