### ISSUE TITLE
IdaInfo structure changed in 7.?

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/python-idb#63]
fields now appear to be `pack_dx`'d

probably need separate handlers for each version.

the arch bitness is stored in the flags here, so worth parsing

![image](https://user-images.githubusercontent.com/156560/54723148-3ae15180-4b2c-11e9-9565-98c35c6d2d73.png)

**Comment by williballenthin** [comment]
![image](https://user-images.githubusercontent.com/156560/54723200-649a7880-4b2c-11e9-8e95-634b2a742ea4.png)

**Comment by williballenthin** [comment]
match the `pack_dx(struct offset)` offsets with those declared here: https://github.com/idapython/src/blob/master/python/idc.py#L1812

**Comment by williballenthin** [comment]
this remains an issue, and its annoying because it blocks simple queries like "what bitness is this IDB?"

**Comment by imbillow** [comment]
> ![image](https://user-images.githubusercontent.com/156560/54723615-b98abe80-4b2d-11e9-91ee-c977286531b7.png)
> 
> 

hi, I want to know which files by decompiling to obtained these two pictures.

**Comment by williballenthin** [comment]
[ida.dll.i64.zip](https://github.com/williballenthin/python-idb/files/4865917/ida.dll.i64.zip)

**Comment by williballenthin** [comment]
`ida.dll` with MD5 `CC7B2981A2BDF722B8DD791313F5710`

**Comment by imbillow** [comment]
Which version does it belong to?

**Comment by williballenthin** [comment]
closed in #78
