### ISSUE TITLE
doesn't work with python-netnode

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/python-idb#64]
as reported by jay

![image](https://user-images.githubusercontent.com/156560/55978694-9bf0d680-5c4d-11e9-924d-5716203708d0.png)

![image](https://user-images.githubusercontent.com/156560/55978698-a3b07b00-5c4d-11e9-8c98-5f881ba24e34.png)

**Comment by XVilka** [comment]
A lot has changed in the https://github.com/williballenthin/ida-netnode since. Is this still a problem?

**Comment by williballenthin** [comment]
given that i dont have a test for this, i can't say for sure :-(

lets reopen if the issue comes up again (and get a test added).
