### ISSUE TITLE
flake8: F821 undefined name 'unpack_db'

### ISSUE THREAD

**Issue by cclauss** [williballenthin/python-idb#8]
```
$ flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
./idb/analysis.py:187:32: F821 undefined name 'unpack_db'
        return self._do_unpack(unpack_db)
                               ^
1     F821 undefined name 'unpack_db'
```

**Comment by williballenthin** [comment]
good catch, thanks!

ran across this myself today, but that was by chance, which simply makes me lucky. your use of flake8 is a great idea to improve code quality, so i'll certainly merge that.

closed in 8ad5c4ea80f930e4fb90e828f6421922afbde3b8
